---
title: "Taxi"
author: "Emilie Bruzelius"
date: "April 4, 2015"
output: html_document
---
```{r}
library(dplyr)
library(plyr)
library(ggplot2)
library(reshape)
library(lubridate)
library(bigrquery)
library(RCurl)
```

```{r}
taxi1 <- read.csv("~/Desktop/R/taxi1.csv")
         View(taxi1)
taxi2 <- read.csv("~/Downloads/taxi2.csv")
         View(taxi2)
```

```{r}
taxi <- rbind(taxi1, taxi2)
        View(taxi)
head(taxi)
```

```{r}
names(taxi) <- c("date", "time", "boro", "zip", "lat", "long",
                 "location", "street", "cross", "offstreet",
                 "injuries", "deaths", "ped_injuries", 
                 "ped_deaths", "cyc_injuries", "cyc_deaths", 
                 "mot_injuries", "mot_deaths", "cause1", 
                 "cause2", "cause3", "cause4", "cause5", "key", 
                 "vtype1", "vtype2", "vtype3", "vtype4", 
                 "vtype5")
View(taxi)
head(taxi)
```

```{r}
count(taxi, 'cause1')
cause <- arrange((count(taxi, 'cause1')), desc(freq))
cause$cause1 <-factor(cause$cause1, 
                      levels=cause[order(cause$freq), "cause1"])
p <- ggplot(cause, aes(freq, cause1))
p + geom_point() 
```

Date manipulations
```{r}
date <- as.Date(taxi$date,format = "%m/%d/%Y")
date <- na.omit(date)
date <- as.data.frame(table(date))
names(date) <- c('date','Freq')
date$date <- as.Date(date$date)
date$year<-as.numeric(as.POSIXlt(date$date)$year+1900)
date$month<-as.numeric(as.POSIXlt(date$date)$mon+1)
date$month3<-factor(date$month,levels=as.character(1:12),labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),ordered=TRUE)
date$weekday = as.POSIXlt(date$date)$wday
date$weekday<-factor(date$weekday,levels=rev(1:7),labels=rev(c("Mon","Tue","Wed","Thu","Fri","Sat","Sun")),ordered=TRUE)
date$yearmonth<-as.yearmon(date$date)
date$yearmonth<-factor(date$yearmonth)
date$week <- as.numeric(format(date$date,"%W"))
date<-ddply(date,.(yearmonth),transform,monthweek=1+week-min(week))
date <- na.omit(date)
```


```{r}
time3 <- hm(taxi$time)
hour <- hour(time3)
hour <- as.data.frame(table(hour))
ggplot(aes(x = as.numeric(hour), y = Freq), data = hour) + 
  geom_line()
```

compute accidents by hour by cause and the proportion accidents at each hour, find outliers
```{r}
hourcause <- data.frame(taxi$time,taxi$cause1,taxi$key)
time <- hm(hourcause$taxi.time)
hod <- hour(time)
hourcause$hod <- hod
hc2 <-count(hourcause, c("taxi.cause1", "hod"))
hc2 <- ddply(hc2, "taxi.cause1", mutate, prop=freq/sum(freq))
overall <- ddply(hc2, "hod", summarise, freq_all = sum(freq))
overall <-mutate(overall, prop_all =freq_all / sum(freq_all))
hc2 <- join(overall, hc2, by = "hod")
#here's where it gets screwed up I think 
devi <- ddply(hc2, "taxi.cause1", summarise, n=sum(freq), dist=mean(prop - prop_all^2))
devi <- subset(devi, n > 50)
devi$resid <- resid(rlm(log(dist) ~ log(n), data = devi))
unusual <- subset(devi, resid > 1.5)
hod_unusual_big <- match_df(hc2, subset(unusual, n>50))
hod_unusual_sml <- match_df(hc2, subset(unusual, n<=50)) 
```

```{r}

```




